/*
 * This source file was generated by the Gradle 'init' task
 */
package dsajava;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class LinkedListTest {
    @Test
    void testCreation() {
        System.out.println("Running tests");
        LinkedList linkedList = new LinkedList(0);
        linkedList.append(1);
        linkedList.append(2);
        System.out.println(linkedList);
        assertEquals(3, linkedList.length);
        assertEquals(linkedList.head.value, 0);
        assertEquals(linkedList.tail.value, 2);

    }
}
